### ISSUE TITLE
When executing after correct compiling,,,

### ISSUE THREAD

**Issue by ghost** [Banbury/cartwheel-3d#5]
At first, I downloaded all files. Then I could finish compiling correctly.
As next step, I executed your program but my visual studio 2008 requires PDB files as follows.
How can I solve this problem and can run your codes without any trouble.
Please help with your kindness.

python.exe	C:\cartwheel\lib\Python26\python.exe	Symbols not loaded.		[2648] python.exe: Native
ntdll.dll	C:\Windows\SysWOW64\ntdll.dll	Symbols not loaded.	6.1.7600.16385 (win7_rtm.090713-1255)	[2648] python.exe: Native
kernel32.dll	C:\Windows\SysWOW64\kernel32.dll	Symbols not loaded.	6.1.7601.18015 (win7sp1_gdr.121129-1432)	[2648] python.exe: Native
KernelBase.dll	C:\Windows\SysWOW64\KernelBase.dll	Symbols not loaded.	6.1.7601.18015 (win7sp1_gdr.121129-1432)	[2648] python.exe: Native
python26.dll	C:\cartwheel\lib\Python26\python26.dll	Symbols not loaded.	2.06.2150.1013	[2648] python.exe: Native
user32.dll	C:\Windows\SysWOW64\user32.dll	Symbols not loaded.	6.1.7601.17514 (win7sp1_rtm.101119-1850)	[2648] python.exe: Native
gdi32.dll	C:\Windows\SysWOW64\gdi32.dll	Symbols not loaded.	6.1.7601.19091 (win7sp1_gdr.151208-0600)	[2648] python.exe: Native
lpk.dll	C:\Windows\SysWOW64\lpk.dll	Symbols not loaded.	6.1.7601.18985 (win7sp1_gdr.150901-1452)	[2648] python.exe: Native
usp10.dll	C:\Windows\SysWOW64\usp10.dll	Symbols not loaded.	1.0626.7601.19054 (win7sp1_gdr.151103-0600)	[2648] python.exe: Native
msvcrt.dll	C:\Windows\SysWOW64\msvcrt.dll	Symbols not loaded.	7.0.7601.17744 (win7sp1_gdr.111215-1535)	[2648] python.exe: Native
advapi32.dll	C:\Windows\SysWOW64\advapi32.dll	Symbols not loaded.	6.1.7601.19135 (win7sp1_gdr.160121-1718)	[2648] python.exe: Native
sechost.dll	C:\Windows\SysWOW64\sechost.dll	Symbols not loaded.	6.1.7600.16385 (win7_rtm.090713-1255)	[2648] python.exe: Native
rpcrt4.dll	C:\Windows\SysWOW64\rpcrt4.dll	Symbols not loaded.	6.1.7600.16385 (win7_rtm.090713-1255)	[2648] python.exe: Native
sspicli.dll	C:\Windows\SysWOW64\sspicli.dll	Symbols not loaded.	6.1.7601.19135 (win7sp1_gdr.160121-1718)	[2648] python.exe: Native
cryptbase.dll	C:\Windows\SysWOW64\cryptbase.dll	Symbols not loaded.	6.1.7601.19135 (win7sp1_gdr.160121-1718)	[2648] python.exe: Native
shell32.dll	C:\Windows\SysWOW64\shell32.dll	Symbols not loaded.	6.1.7601.19135 (win7sp1_gdr.160121-1718)	[2648] python.exe: Native
shlwapi.dll	C:\Windows\SysWOW64\shlwapi.dll	Symbols not loaded.	6.1.7600.16385 (win7_rtm.090713-1255)	[2648] python.exe: Native
msvcr90.dll	C:\Windows\winsxs\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\msvcr90.dll	Symbols not loaded.	9.00.30729.6161	[2648] python.exe: Native
imm32.dll	C:\Windows\SysWOW64\imm32.dll	Symbols not loaded.	6.1.7601.17514 (win7sp1_rtm.101119-1850)	[2648] python.exe: Native
msctf.dll	C:\Windows\SysWOW64\msctf.dll	Symbols not loaded.	6.1.7600.16385 (win7_rtm.090713-1255)	[2648] python.exe: Native
nvinit.dll	C:\Windows\SysWOW64\nvinit.dll	Symbols not loaded.	9.18.13.3235	[2648] python.exe: Native
detoured.dll	C:\Program Files (x86)\NVIDIA Corporation\coprocmanager\detoured.dll	Symbols not loaded.		[2648] python.exe: Native
Nvd3d9wrap.dll	C:\Program Files (x86)\NVIDIA Corporation\coprocmanager\Nvd3d9wrap.dll	Symbols not loaded.	9.18.13.3235	[2648] python.exe: Native
setupapi.dll	C:\Windows\SysWOW64\setupapi.dll	Symbols not loaded.	6.1.7600.16385 (win7_rtm.090713-1255)	[2648] python.exe: Native
cfgmgr32.dll	C:\Windows\SysWOW64\cfgmgr32.dll	Symbols not loaded.	6.1.7601.17621 (win7sp1_gdr.110523-2108)	[2648] python.exe: Native
oleaut32.dll	C:\Windows\SysWOW64\oleaut32.dll	Symbols not loaded.	6.01.7601.18679	[2648] python.exe: Native
ole32.dll	C:\Windows\SysWOW64\ole32.dll	Symbols not loaded.	6.1.7600.16385 (win7_rtm.090713-1255)	[2648] python.exe: Native
devobj.dll	C:\Windows\SysWOW64\devobj.dll	Symbols not loaded.	6.1.7601.17621 (win7sp1_gdr.110523-2108)	[2648] python.exe: Native
nvdxgiwrap.dll	C:\Program Files (x86)\NVIDIA Corporation\coprocmanager\nvdxgiwrap.dll	Symbols not loaded.	9.18.13.3235	[2648] python.exe: Native
_MathLib.pyd	C:\cartwheel\cartwheel-3d\binaries\Release\_MathLib.pyd	Binary was not built with debug information.		[2648] python.exe: Native
_Utils.pyd	C:\cartwheel\cartwheel-3d\binaries\Release\_Utils.pyd	Binary was not built with debug information.		[2648] python.exe: Native
msvcp90.dll	C:\Windows\winsxs\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\msvcp90.dll	Symbols not loaded.	9.00.30729.6161	[2648] python.exe: Native
gsl.dll	C:\cartwheel\cartwheel-3d\binaries\Release\gsl.dll	Binary was not built with debug information.		[2648] python.exe: Native

**Comment by Banbury** [comment]
I'm not the author of this software. I just saved it from Google Code. I haven't even tried to build it, for lack of time.

But the messages don't seem to be errors. They just tell you, that python.exe and a bunch of DLLs have no debug symbols. This shouldn't stop you from running the program anyway. You just can't debug python.exe and those DLLs. And under normal circumstances you don't need to. Just ignore those messages.

**Comment by Banbury** [comment]
I guess, it's working now.
